### ISSUE TITLE
Shared libraries

### ISSUE THREAD

**Issue by nxrighthere** [zpl-c/enet#1]
Unfortunately (or fortunately), I'm not a C developer, and at the moment I'm using C# wrapper to work with the old version of ENet. It would be great if you could provide the shared libraries (DLL for Windows at least) in the release section. People like me would be grateful for that.

**Comment by inlife** [comment]
Yes, most likely we will add them. Especially for the next version we are planning to do.

Current version has no incompatible differences from original fork, so it's static lib/dll can be used for now.

**Comment by nxrighthere** [comment]
I just released [BenchmarkNet](https://github.com/nxrighthere/BenchmarkNet) for stress testing the reliable UDP networking libraries (including ENet). If you are interested, [here](https://forum.unity.com/threads/benchmarknet-stress-test-for-enet-unet-litenetlib-lidgren-and-miniudp.512507) is the latest results.

**Comment by inlife** [comment]
Oh that is nice! Thank you.
Also, tbh, totally did not except UNet to have such a bad set of results )

**Comment by nxrighthere** [comment]
[ENet](https://s13.postimg.org/bfbhgi9if/ENet_3000_clients.png) (3000 clients) on 6-core Intel Xeon...
CPU usage 34%, memory consumption 200 megabytes.

**Comment by inlife** [comment]
oh, btw, @nxrighthere wanted to ask, which bindings for ENet did you use?

**Comment by nxrighthere** [comment]
https://github.com/NateShoffner/ENetSharp

**Comment by inlife** [comment]
thank you

**Comment by inlife** [comment]
@nxrighthere do you have a discord btw?

**Comment by nxrighthere** [comment]
Yes, and I also speak russian.

**Comment by inlife** [comment]
oh hey, me too :D
can you join, so we could exchange some pms
https://discord.gg/2fZVEym

thank you!
