### ISSUE TITLE
enet_address_get_host_ip does not return valid ipv4

### ISSUE THREAD

**Issue by RootKiller** [zpl-c/enet#14]
Hi!

When calling enet_address_get_host_ip on ipv4 peer it returns the following string `::ffff:127.0.0.1`

**Comment by nxrighthere** [comment]
This is because IPv4-mapped IPv6 addresses are used, can be solved [this](https://github.com/nxrighthere/ENet-CSharp/blob/master/Source/Native/enet.h#L4389) way or by probing a string for `:` character and shrinking it by first 7 bytes.
