### ISSUE TITLE
Possible to get source code to build for embeded Linux system

### ISSUE THREAD

**Issue by lichangche** [zpl-c/enet#15]
Dear contributors, 

Not sure if it installation problem or the enet source code is a secrete in this new implementation?

I tried to install but get the following warning - and I cannot find the source code.

/home/xxx/workspace/enet/build
└── enet.c@2.1.3 

npm WARN enoent ENOENT: no such file or directory, open '/home/uta/workspace/enet/build/package.json'
npm WARN build No description
npm WARN build No repository field.
npm WARN build No README data
npm WARN build No license field.

If not a secret, is it possible to share me the source code so that I can embed the project in my embedded Linux?

Thanks,
Carl

**Comment by inlife** [comment]
Hello Carl,

Sure thing, just download this file, and add it to your project:
https://github.com/zpl-c/enet/blob/master/include/enet.h

And in one of your source code files (*.c/*.cpp file) do `#define ENET_IMPLEMENTATION` before including `enet.h`

That's it! :)
Cheers!
