### ISSUE TITLE
Improve code style consistency

### ISSUE THREAD

**Issue by OptoCloud** [zpl-c/enet#23]
Different code styles are scattered troughout the library
```cpp
void someFunc() {
  if (somCond) {
  }
}

void someSecondFunc()
{
  if (somCond) {
  }
}

void someThirdFunc() {
  if (somCond)
  {
  }
}
```
More inline documentation would be nice as well

**Comment by warmwaffles** [comment]
@OptoCloud one solution is to use `clang-format` to enforce a standard. Although it will cause a lot of churn within the library.
