### ISSUE TITLE
Handful of minor warnings and static analysis improvements

### ISSUE THREAD

**Issue by kcgen** [zpl-c/enet#35]
We're planning to use ZPL's Enet on the DOSBox Staging project for serial, nullmodem, and softmodem transport, and hit some issues flagged by the PVS Studio static analyzer.

We want to follow whatever approach you'd prefer to get these fixed up.   I can send them all in one ticket, or open one-by-one?  Whatever is easier for you to track.

**Comment by inlife** [comment]
Hey @kcgen 

It's awesome!

Let's do it like this, if there are more than 5 tickets then it makes sense to bundle it up into a single one, but if it is 5 or less, we would really appreciate having them separated.

How does that sound?

Cheers

**Comment by kcgen** [comment]
Thank you @inlife!

Here's the analysis package (self-contained meant for offline viewing):

[pvs-report-2021-11-16_T0216-d414a30d.tar.gz](https://github.com/zpl-c/enet/files/7548378/pvs-report-2021-11-16_T0216-d414a30d.tar.gz)

Unzip it and then open the `index.html` inside the `general/` directory.

It will bring up an interactive table:

![2021-11-16_08-49](https://user-images.githubusercontent.com/1557255/142031764-9903cedf-dd0a-4ecc-86a2-c7aced33a3c7.png)

The **`source:line`** links will jump into a copy of the code, and describe the issue in detail, like this:

![2021-11-16_09-12](https://user-images.githubusercontent.com/1557255/142032774-adee649b-6c8c-485f-81e3-b53547a235b4.png)

And the "V" issue link will take you to a detailed explanation and tips on how to fix it, like this:

![2021-11-16_09-12_1](https://user-images.githubusercontent.com/1557255/142032940-05412e3c-e3c2-4499-a0d3-549ef67c8d42.png)

We have found these reports very helpful. Long live Enet :rocket:

**Comment by kcgen** [comment]
@inlife , if we can help solve some of these, would you be open to use pushing them as PR's here?

**Comment by inlife** [comment]
For sure!
