### ISSUE TITLE
enet_packet_resize is missing

### ISSUE THREAD

**Issue by Steamgjk** [zpl-c/enet#44]
While I was testing with a small demo, I found enet_packet_resize is defined by not implemented in the single-header file enet.h.

Is there any special consideration for dropping the API?

**Comment by inlife** [comment]
I don't think it was a conscious decision, most likely done by mistake.

**Comment by inlife** [comment]
Ideally, we would like to port it back here in some time. However, if you are open to a contribution, it would be highly welcomed! 🎉

**Comment by zpl-zak** [comment]
I will add it today. It must've been lost during one of our large refactors; sorry about that!

**Comment by zpl-zak** [comment]
enet_packet_resize is available again as of https://github.com/zpl-c/enet/commit/42c03e1ff26bf5873a9de8c52645ffd3ac9687e4
