### ISSUE TITLE
ENET_HOST_ANY

### ISSUE THREAD

**Issue by wpbirney** [zpl-c/enet#7]
using ENET_HOST_ANY, makes enet listen on the ipv6 device if available ( at least on linux ) 
this isn't a problem but i was wondering if there is a ENET_HOST_ANY_ variant that forces ipv4

I dont see one in the source, but i figure i could add it quite easily

*edit 
further digging seems that ENetAddress expects an in6addr and seems to *only* support ipv6 now

**Comment by inlife** [comment]
Currently there is no way to force listen to ipv4 only. However, it supports both ipv4 and ipv6, not just ipv6.

Have you tried binding the ipv4 address, and check wether it's gonna listen to ipv4 only?

**Comment by nxrighthere** [comment]
> further digging seems that ENetAddress expects an in6addr and seems to only support ipv6 now

IPv4 supported via IPv4-mapped IPv6 address.
