### ISSUE TITLE
DTLS.

### ISSUE THREAD

**Issue by Malkverbena** [zpl-c/enet#8]
Is there any plain to implement DTLS support ?

**Comment by inlife** [comment]
Hey @Malkverbena !

I don't think so, not at the moment anyway.  
However I have a question for you, how do you see the potential implementation/integration of such thing?

Thank you

**Comment by zaklaus** [comment]
There's no plan to implement encryption into our enet fork. Thanks for the suggestion.

**Comment by Malkverbena** [comment]
@inlife I never took the time to understand Enet deeply, I just can't point the best way to it. But there is a library that I think could help. 
Also, such king of resource can bring a lot of attention to this fork...

https://tls.mbed.org/
